/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.dao.MotoristaDAO;
import model.bean.Motorista;

/**
 *
 * @author gabri
 */
public class JFListarMotorista extends javax.swing.JFrame {

    /**
     * Creates new form JFListarMotorista
     */
    public JFListarMotorista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTMotorista = new javax.swing.JTable();
        jBnCadastrar = new javax.swing.JButton();
        jBnEditar = new javax.swing.JButton();
        jBnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Listar Motorista");

        JTMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idMotorista", "nome", "genero", "RG", "CPF", "numero", "email", "senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTMotorista);

        jBnCadastrar.setText("Cadastrar Motorista");
        jBnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnCadastrarActionPerformed(evt);
            }
        });

        jBnEditar.setText("Editar Motorista");
        jBnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnEditarActionPerformed(evt);
            }
        });

        jBnExcluir.setText("Excluir Motorista");
        jBnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBnCadastrar)
                        .addGap(61, 61, 61)
                        .addComponent(jBnEditar)
                        .addGap(60, 60, 60)
                        .addComponent(jBnExcluir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnCadastrar)
                    .addComponent(jBnEditar)
                    .addComponent(jBnExcluir))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jBnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnCadastrarActionPerformed

    private void jBnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnEditarActionPerformed
                if(JTMotorista.getSelectedRow() != -1){
            int motoristaSelecionado = (int)JTMotorista.getValueAt
                (JTMotorista.getSelectedRow(), 0);
            JFAtualizarMotorista av = new JFAtualizarMotorista(motoristaSelecionado);
            av.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um motorista!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
        readJTable();
                                           

    }//GEN-LAST:event_jBnEditarActionPerformed

    private void jBnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnExcluirActionPerformed
         if(JTMotorista.getSelectedRow() != -1){
            int opcao = JOptionPane.showConfirmDialog(null,
                    "Deseja excluir o motorista selecionado?", "Exclusão",
                    JOptionPane.YES_NO_OPTION);
            if(opcao == 0){
                MotoristaDAO dao = new MotoristaDAO();
                Motorista m = new Motorista();
                m.setIdMotorista((int)JTMotorista.getValueAt(JTMotorista.getSelectedRow(), 0));
                dao.delete(m);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma vaga!","Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
        readJTable();
    }//GEN-LAST:event_jBnExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       readJTable();
    }//GEN-LAST:event_formWindowOpened
 public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) JTMotorista.getModel();
        modelo.setNumRows(0);
        MotoristaDAO dao = new MotoristaDAO();
        for(Motorista m: dao.read()){
            modelo.addRow(new Object[]{
            m.getIdMotorista(),
            m.getNome(),
            m.getGenero(),
            m.getRG(),
            m.getCPF(),
            m.getNumero(),
            m.getEmail(),
            m.getSenha()
        });
        
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFListarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFListarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFListarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFListarMotorista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFListarMotorista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTMotorista;
    private javax.swing.JButton jBnCadastrar;
    private javax.swing.JButton jBnEditar;
    private javax.swing.JButton jBnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
